### ISSUE TITLE
Remapping only works with Numlock off

### ISSUE THREAD

**Issue by AuwersK** [lostallmymoney/Razer_Mouse_Linux#10]
How do I get the remapping to work with numlock on?
I want my mouse's sidebuttons to simulate a keypress on the numpad. 

1 on mouse = simulate 1 press on keypad

**Comment by AuwersK** [comment]
i found the solution in the closed issues already i was also using key=KP_1 instead of just key=1 etc

**Comment by lostallmymoney** [comment]
My naga buttons are somewhat worn down and they sometimes unclick and then re clicks instantly making key unstable sometimes ahah. Just a thing to consider you might use keyclickOnPress if you don't need extended presses on your keypad
1111111.1111

**Comment by AuwersK** [comment]
I also noticed when I bind 1 - key=KP_1 it also triggers SHIFT_L first but I don’t know why
