### ISSUE TITLE
xdotool mouseClick doesn't seem to work at all

### ISSUE THREAD

**Issue by NysNight** [lostallmymoney/Razer_Mouse_Linux#11]
So I've been trying them all, 1-9

`config=defaultConfig

1 - key=6

2 - mouseClick=9

3 - key=8

4 - key=v

5 - mouseClick=8

6 - key=9

7 - key=F3

8 - key=i

9 - key=0

10 - key=F4

11 - key=ctrl+w

12 - key=end

13 - key=F5

14 - key=F1

configEnd`

This is the config I want to run, but everything except the mouceClicks seem to work.
I don't know if capitalization has an effect in this case, but your GUIDEKeymap has mouseclick while in the configuration section you have mouseClick. Doesn't really matter, neither works. Can't even simulate a normal '1' click.

In the other issue you mentioned trying to remove the xdotool dependency, so I guess this issue would leave that way too, but I'm still looking for a replacement. In the end I'm just trying to bind the "forwards" and "backwards" key to side-button 2 and 5

Naga Epic Chroma mouse, btw, on Manjaro

**Comment by lostallmymoney** [comment]
I believe this is an older feature that I removed.  To execute mouseClick try run=xdotool click 8
I'll look into this


________________________________
From: NysNight ***@***.***>
Sent: Monday, August 16, 2021, 9:27 p.m.
To: lostallmymoney/Razer_Mouse_Linux
Cc: Subscribed
Subject: [lostallmymoney/Razer_Mouse_Linux] xdotool mouseClick doesn't seem to work at all (#11)


So I've been trying them all, 1-9

`config=defaultConfig

1 - key=6

2 - mouseClick=9

3 - key=8

4 - key=v

5 - mouseClick=8

6 - key=9

7 - key=F3

8 - key=i

9 - key=0

10 - key=F4

11 - key=ctrl+w

12 - key=end

13 - key=F5

14 - key=F1

configEnd`

This is the config I want to run, but everything except the mouceClicks seem to work.
I don't know if capitalization has an effect in this case, but your GUIDEKeymap has mouseclick while in the configuration section you have mouseClick. Doesn't really matter, neither works. Can't even simulate a normal '1' click.

In the other issue you mentioned trying to remove the xdotool dependency, so I guess this issue would leave that way too, but I'm still looking for a replacement. In the end I'm just trying to bind the "forwards" and "backwards" key to side-button 2 and 5

Naga Epic Chroma mouse, btw.

**Comment by NysNight** [comment]
You are correct. the run=xdotool method works. As someone who's just coming to this tool and reading the old stuff, this wasn't obvious to me.
The alternative hacky method was:
`Alt_L+Right
Alt_L+Left`

but while the run thing doesn't really look as elegant in code, I like it better in terms of result. Thanks for the quick response :+1:
