### ISSUE TITLE
Support for Naga pro Wireless.

### ISSUE THREAD

**Issue by Stibax** [lostallmymoney/Razer_Mouse_Linux#13]
Hi,
I tried to install the keypadmapper but it seems not working. I've installed the openrazer with latest commit and it works but it doesn't support the keypad binding.
Thanks.

**Comment by lostallmymoney** [comment]
You need to find the name of the driver files. Then add them to the list before compiling. Should be as simple as that. Look up the path for other mices
________________________________
From: Stibax ***@***.***>
Sent: Thursday, December 2, 2021 1:53:35 PM
To: lostallmymoney/Razer_Mouse_Linux ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lostallmymoney/Razer_Mouse_Linux] Support for Naga pro Wireless. (Issue #13)


Hi,
I tried to install the keypadmapper but it seems not working. I've installed the openrazer with latest commit and it works but it doesn't support the keypad binding.
Thanks.

**Comment by Stibax** [comment]
Hi,
thanks for your help. Sorry i'm a noob. Based on your clue, i've done the following:
edit the file naga.cpp
i have added:
devices.emplace_back("/dev/input/by-id/usb-Razer_Razer_Naga_Pro_000000000000-if02-event-kbd" , "/dev/input/by-id/usb-Razer_Razer_Naga_Pro_000000000000-event-mouse");                // NAGA PRO WIRELESS
sh install.sh
I try to press the button 1 that, if i understand right, in the default config is bind with audio mute, nothing happens and also the other buttons do nothing.
In the folder /dev/input/by-id/ i have other files related to naga pro, but i've choose those similar to the other devices.
I've missed something?

**Comment by lostallmymoney** [comment]
Try all of them. And give me news. You're on the right track. Maybe if you can get a list of your naga files and i could help you if there is a lot but in my case i noticed there is about 2 or 3 sets of files and only one worked.
I'm not sure but i think remembering there was no correlation with the other name's numberings ;)
Maybe making sure all the files are uninstalled correctly afterwards both in root and non root could make a difference. Might be a bug i can fix !:)
________________________________

**Comment by lostallmymoney** [comment]
Also try testing your "xdotool press a". You said in 1st post that it was working, what do you mean by that ?
________________________________

**Comment by Stibax** [comment]
hi,
I mean that if i compile openrazer master branch naga pro doesn't work, to do it works i have to compile openrazer with the latest commit. 
In the folder i have, related to naga pro, the following files:

usb-Razer_Razer_Naga_Pro_000000000000-event-if03
usb-Razer_Razer_Naga_Pro_000000000000-event-mouse
usb-Razer_Razer_Naga_Pro_000000000000-if01-event-mouse
usb-Razer_Razer_Naga_Pro_000000000000-if01-mouse
usb-Razer_Razer_Naga_Pro_000000000000-if02-event-kbd
usb-Razer_Razer_Naga_Pro_000000000000-mouse

To uninstall i run naga uninstall, and delete /home/$user/.naga 
/etc/udev/rules.d/80-naga.rules
/user/local/bin naga* and kilroot.sh
Right? There was something else?
Thanks for your help.
I will try compile with other files.

**Comment by Stibax** [comment]
Can i put more than two files in the devices.emplace_back line?

**Comment by lostallmymoney** [comment]
No as it will latch onto the first one it will find. I think there is 2 files tho
________________________________

**Comment by lostallmymoney** [comment]
Pretty sure it'll work with the right one, also after deleting make sure to install rooted and to copy the config files to your home/.naga and root home naga and try running as root
________________________________

**Comment by Stibax** [comment]
It works!!!!!!!!!!! The stupid error was mine! Instead edit naga.cpp inside /src i have edit the one in the parent folder. sorry.
So to make it works with Naga pro Wireless the line to add is the following:
devices.emplace_back("/dev/input/by-id/usb-Razer_Razer_Naga_Pro_000000000000-if02-event-kbd" , "/dev/input/by-id/usb-Razer_Razer_Naga_Pro_000000000000-event-mouse");                // NAGA PRO WIRELESS  

Thank you very much for your work and for the help.
 Now let's go to customize the binding.

**Comment by lostallmymoney** [comment]
Do you wanna try merging it or i can credit you ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lostallmymoney** [comment]
Damn the good old signature settings reset then it spawns under your keyboard
________________________________
