### ISSUE TITLE
String fuction

### ISSUE THREAD

**Issue by Stibax** [lostallmymoney/Razer_Mouse_Linux#14]
Hi,
i've notice that if i asign a string like this:
5 - string=name@gmail.com 
it prints only namegmail.com without "@"
I miss something?
Thanks

**Comment by lostallmymoney** [comment]
Problem with xdotool. Try segmenting it :
5-string=name
5-keyclick=@
5-string=gmail.com
I have worked on a fix but never finished it, i might try to finish it up.
________________________________
From: Stibax ***@***.***>
Sent: Wednesday, December 8, 2021 1:34:30 PM
To: lostallmymoney/Razer_Mouse_Linux ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lostallmymoney/Razer_Mouse_Linux] String fuction (Issue #14)


Hi,
i've notice that if i asign a string like this:
5 - ***@***.******@***.***>
it prints only namegmail.com without "@"
I miss something?
Thanks

**Comment by Stibax** [comment]
No it wouldn't print the @ symbol. Maybe because in the italian layout keyboard to make @ i have to press ALTGR end not shift?

**Comment by lostallmymoney** [comment]
Yes exactly, you can try to switch xdotool for any other command that can write @ lol.. i'll post the fix prototype as branch in 5 minutes for you, I was able to fix the issue on apostrophee ' , it should probably work with @ but it is poorly implemented. I don't have lots of time rn it's not implemented maybe you can adapt it for your and it maybe has bugs in other places.
________________________________

**Comment by Stibax** [comment]
Thanks lostallmymoney, i will try and i report you back.
Have a nice day.

**Comment by lostallmymoney** [comment]
Try the new beta branch :) should work pretty good for @ and ' . Might fail on weird chars tho. The file is a bit messy at the top I got code from an old lib with deprecated functions that still work better than the other stuff lol. People on the xdotool git are also searching for the fix with some progress maybe.

**Comment by lostallmymoney** [comment]
https://github.com/lostallmymoney/Razer_Mouse_Linux/tree/Beta

**Comment by lostallmymoney** [comment]
With the optic of accessing a login creds manager I was thinking of making encrypted configs that need to be opened with the right button combo. Then you can have your in house creds bank

**Comment by lostallmymoney** [comment]
I made an update if you want to try it you can now hold special keys down, although releasing special keys will release them all for now.

**Comment by Stibax** [comment]
Hi,
I've install the new version.
I've meet a problem with compiler (install.sh) give me the following error:
g++-10 command not found.
I've resolved, i think, editing the install.sh and change g++-10 in g++, but i don't know if my guss was correct. In any way, with this modification, the installation goes well.
Now i don't understand how, with the new version, i can print name@gmail.com.
I've have tried:
string=name
key=@
stringRelease=gmail.com
no @  printed
I've tried:
string=name
KeyClick=Alt_R
key=ò
stringRelease=gmail.com

and other configuration.

I like your idea of making encrypted configs. 
Thanks again.

**Comment by lostallmymoney** [comment]
Try the config i included in the new version. The command is special=@ or specialRelease=@ (press at button release)
________________________________

**Comment by lostallmymoney** [comment]
And yes thanks for your feedback for g++10 i was trying stuff out and forgot to take it out
________________________________

**Comment by lostallmymoney** [comment]
For normal chars I recommend xdotool as it's nicely implemented but if you need to use special chars that's where the libfakekey comes in play. Now since they both have features that we need both are included and special uses libfakekey libraries

**Comment by lostallmymoney** [comment]
Oh I found a bug it seems xserver connections are not disconnecting and at some point reach a limit crashing the tool. I'll try to fix it later, weird bug. It should only affect you if you write your email address 100 times tho

**Comment by lostallmymoney** [comment]
There, every session now closes properly. Current setup looks like it has everything right ;)

**Comment by lostallmymoney** [comment]
Now I removed the old xdotool strings and replaced it with special, so if you want to try the new version be sure to merge all special chars along with normal chars into strings. This should make it simpler. Only when trying to press all the ascii chars at once do i get any noticeable lag, when writing normal text it can write whole paragraphs. Tell me if it's working good on your side !

**Comment by Stibax** [comment]
Great job! It works now print @ without any lag.
I have found a little error, in install.sh where the file nagakillroot.sh  has a different name in src folder (killroot.sh) so when compile gives error. 
I have also try to add the following line in naga.cp (src):
devices.emplace_back("/dev/input/by-id/usb-1532_Razer_Naga_Pro_000000000000-if02-event-kbd" , "usb-1532_Razer_Naga_Pro_000000000000-event-mouse");                                  // NAGA PRO 
because when i plug the mouse for charging it doesn't work because in /dev/input/by-id/ the device files change, so i was thinking that adding that line when i charge the mouse naga daemon switch the driver, but it doesn't work.
Thanks thanks for the great work!
Have a nice evening.

**Comment by lostallmymoney** [comment]
It should work if you place your line before all the others
________________________________

**Comment by Stibax** [comment]
Sorry it was my error! I forgot the folder in the second device mouse event. So it works great plugged and unplugged in wireless mode! So the right line (at the bottom works) is the following:

devices.emplace_back("/dev/input/by-id/usb-1532_Razer_Naga_Pro_000000000000-if02-event-kbd" , "/dev/input/by-id/usb-1532_Razer_Naga_Pro_000000000000-event-mouse");                 // NAGA PRO

Thanks again! Now it's perfect!!!
