### ISSUE TITLE
killroot.sh error

### ISSUE THREAD

**Issue by Stibax** [lostallmymoney/Razer_Mouse_Linux#18]
Hi,
there was an error while sh install.sh, in that script this line:
sudo cp -f ./src/nagakillroot.sh /usr/local/bin/
sudo chmod 755 /usr/local/bin/nagakillroot.sh

the file name nagakillroot.sh it's wrong because in the src folder the name of the file is: 
killroot.sh

Have a nice day.

**Comment by lostallmymoney** [comment]
Thanks, that was from the 1st nameI had made for the file.

**Comment by lostallmymoney** [comment]
I changed it back to nagaKillRoot since I want the name to be linked to naga.
