### ISSUE TITLE
Buttons 2, 3, and 7 do not work on Naga Trinity.

### ISSUE THREAD

**Issue by BVenturaDev** [lostallmymoney/Razer_Mouse_Linux#20]
I have bound 1-12 to their respective numbers, and found that the keys 2,3, and 7 do not output anything regardless of what I bind them too.  I am not seeing any errors.  This is with the Naga Trinity.  Worth noting that before trying this fork I tried the original Naga Keymapper project with the same error, was hoping this fork would solve it.  Testing in evtest reveals these buttons are not outputting.

**Comment by lostallmymoney** [comment]
Can you tell me what was the issue ? Thanks !

**Comment by lostallmymoney** [comment]
If your config file is ok, and your mouse is working, i'd think it's a matter of device file.

**Comment by BVenturaDev** [comment]
Sorry for not updating with answer, it was really dumb. My sensor was dusty and I spent 2 hours trying to debug instead of just cleaning the inputs.  Thanks for the work on this tool.
