### ISSUE TITLE
naga service not starting on Wayland

### ISSUE THREAD

**Issue by AsimAJ33** [lostallmymoney/Razer_Mouse_Linux#36]
Hi there,

Your project is the closest I've come to getting my Naga Pro to work so thanks for that firstly.

I'm running Ubuntu 23 Wayland and during the install script, I chose to not install for X11 as I only use Wayland.

I can't get the naga service to start, after looking at the debug logs this is what I see.  Is it a simple case of this project isn't Wayland ready yet or am I being silly and doing something wrong?

Happy to provide other logs etc

```Starting naga debug, logs :
Jun 07 16:13:06 ubenbro systemd[1]: naga.service: Failed with result 'exit-code'.
Jun 07 16:13:59 ubenbro systemd[1]: Started naga.service - Custom key bindings for the side panel of razer mouses..
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84906]: dotoold: no process found
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84907]: bash: line 1: dotoold: command not found
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84908]: Stopping possible naga daemon
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84927]: WARNING: running xinput against an Xwayland server. See the xinput man page for details.
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84935]: WARNING: running xinput against an Xwayland server. See the xinput man page for details.
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84935]: unable to find device ''
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84908]: Reading from: /dev/input/by-id/usb-Razer_Razer_Naga_Pro_000000000000-if02-event-kbd
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84908]:  and /dev/input/by-id/usb-Razer_Razer_Naga_Pro_000000000000-event-mouse
Jun 07 16:14:07 ubenbro nagaServerCatcher.sh[84908]: Error calling method: Object does not exist at path “/org/gnome/Shell/Extensions/WindowsExt”
Jun 07 16:14:07 ubenbro nagaServerCatcher.sh[84908]: WindowNameLog :
Jun 07 16:14:07 ubenbro nagaServerCatcher.sh[84899]: Segmentation fault (core dumped)
Jun 07 16:14:07 ubenbro systemd[1]: naga.service: Main process exited, code=exited, status=139/n/a
Jun 07 16:14:07 ubenbro systemd[1]: naga.service: Failed with result 'exit-code'.```

**Comment by lostallmymoney** [comment]
It also looks like the wayland extension didn't properly install or something as such. Try finding why dotool does not install and you should have part of the issue solved (altough the wayland version lacks a bit with the fake keys it can run casual stuff pretty alright).
________________________________
From: AsimAJ33 ***@***.***>
Sent: Wednesday, June 7, 2023 11:20:08 AM
To: lostallmymoney/Razer_Mouse_Linux ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lostallmymoney/Razer_Mouse_Linux] naga service not starting on Wayland (Issue #36)


Hi there,

Your project is the closest I've come to getting my Naga Pro to work so thanks for that firstly.

I'm running Ubuntu 23 Wayland and during the install script, I chose to not install for X11 as I only use Wayland.

I can't get the naga service to start, after looking at the debug logs this is what I see. Is it a simple case of this project isn't Wayland ready yet or am I being silly and doing something wrong?

Happy to provide other logs etc

Jun 07 16:13:06 ubenbro systemd[1]: naga.service: Failed with result 'exit-code'.
Jun 07 16:13:59 ubenbro systemd[1]: Started naga.service - Custom key bindings for the side panel of razer mouses..
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84906]: dotoold: no process found
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84907]: bash: line 1: dotoold: command not found
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84908]: Stopping possible naga daemon
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84927]: WARNING: running xinput against an Xwayland server. See the xinput man page for details.
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84935]: WARNING: running xinput against an Xwayland server. See the xinput man page for details.
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84935]: unable to find device ''
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84908]: Reading from: /dev/input/by-id/usb-Razer_Razer_Naga_Pro_000000000000-if02-event-kbd
Jun 07 16:13:59 ubenbro nagaServerCatcher.sh[84908]:  and /dev/input/by-id/usb-Razer_Razer_Naga_Pro_000000000000-event-mouse
Jun 07 16:14:07 ubenbro nagaServerCatcher.sh[84908]: Error calling method: Object does not exist at path “/org/gnome/Shell/Extensions/WindowsExt”
Jun 07 16:14:07 ubenbro nagaServerCatcher.sh[84908]: WindowNameLog :
Jun 07 16:14:07 ubenbro nagaServerCatcher.sh[84899]: Segmentation fault (core dumped)
Jun 07 16:14:07 ubenbro systemd[1]: naga.service: Main process exited, code=exited, status=139/n/a
Jun 07 16:14:07 ubenbro systemd[1]: naga.service: Failed with result 'exit-code'.```

**Comment by AsimAJ33** [comment]
Okay I'm a little further, I've installed dotool but it only works when I use sudo
```
echo type hello | dotool
dotool: failed to create virtual keyboard device: could not open device file
```
When I use sudo
```
echo type hello | sudo dotool
hello
```
So I know that dotool is installed but only sudo can use it, which is going to cause issues issues:

If I run
```
naga debug
Starting naga debug, logs :
Jun 12 17:58:40 ubenbro systemd[1]: Started naga.service - Custom key bindings for the side panel of razer mouses..
Jun 12 17:58:40 ubenbro nagaServerCatcher.sh[1910]: dotoold: no process found
Jun 12 17:58:40 ubenbro nagaServerCatcher.sh[1912]: Stopping possible naga daemon
```
We can see that as before, the naga daemon can't see that dotool is installed. 

I thought about just doing `sudo naga debug` so that sudo could run the naga daemon and also see dotool but that doesn't work either
```
sudo naga debug
sudo: naga: command not found
```
Apologies for the seemingly silly issue but I feel like I'm really close to getting this working so would appreciate your help.

Thanks

**Comment by lostallmymoney** [comment]
Dotool needs a udev rule. Try installing for x11 too in case there are shared dependencies. After installing dotool there is a little trickery to run a dotoold (daemon) then NagaWayland sends stuff to dotoold. From what I can see a lot went wrong in your install since you do not have the set alias naga. I will try installing on wayland again in a few days. Tbh idk how both features went wrong. Especially with the gnome extension.
Were you online when you installed ?
Oh and if you read about the bugs you'll learn that sometimes ubuntu will boot on x11 or wayland for no reason.
________________________________

**Comment by AsimAJ33** [comment]
Just an update, I've tried installing on X11 too and yes I was online when I installed but still can't get your app running so my naga is still sadly useless on Ubuntu :(

**Comment by lostallmymoney** [comment]
Hey sorry man I really wasn't around my PC. Here is the patch your mouse will work under wayland now ahah !

**Comment by lostallmymoney** [comment]
Damn idk what happened to wayland version ahah. Keeping 2 versions is messy sometimes. Had to fix some mistake and add back the suffixes.
