### ISSUE TITLE
How to setup simple macros like copy/paste?

### ISSUE THREAD

**Issue by Asitis** [lostallmymoney/Razer_Mouse_Linux#40]
Hi! I love the ease of use of this tool, but I can't seem to figure out if there's a possible workaround to have it accept simple macros like copy and paste?

**Comment by lostallmymoney** [comment]
Key or KeyClick depending if you are using x11 or wayland, 
X11 : XF86XK_Paste, XF86XK_Copy, and XF86XK_Cut.
X11 using wayland version : xf86copy, xf86paste, xf86cut.
Wayland : copy, paste, cut.

**Comment by Asitis** [comment]
Appreciate the quick reply! However I tried both `key` and `KeyClick` with both X11 (which im on) and X11 using Wayland commands. I can tell the edits are picked up (previous assigned action is not firing anymore) but there is no copy :| ?

```
1 - key=XF86XK_Copy
4 - key=xf86copy
```

**Comment by lostallmymoney** [comment]
Since you're on X11 it should be easy to find xdotool's keycodes for copy and paste if they have been updated. Please google it and come back with the right keycodes. Also make sure you are trying to paste too ahah.
________________________________

**Comment by Asitis** [comment]
Haha damn I feel like an idiot. It's as simple as setting it up as below:
```
1 - key=ctrl+c
4 - key=ctrl+v
```

Thanks for responding, and pointing me in the right direction. This is an amazing piece of software :ok_hand:
