### ISSUE TITLE
Side button still sends the original key when pressed.

### ISSUE THREAD

**Issue by SirFireball3521** [lostallmymoney/Razer_Mouse_Linux#6]
I rebound the 2nd button to "o", but when I press it, it does this: 2o

This is a razer naga trinity in the 7-button configuration, and I'm using Debian 10.

**Comment by lostallmymoney** [comment]
That's a problem with the xinput script. Try disconnecting and reconnecting the mouse then run the xinput script manually and try again. Maybe the script isn't moved in the right folder.

**Comment by lostallmymoney** [comment]
hmm this might be something else after all.
Easy ways to fix could be changing dev/input/by-id/ file in the naga.cpp
I don't have a 7 button trinity to test

**Comment by SirFireball3521** [comment]
Yeah, reconnecting the mouse and running `naga start` again seemed to work.

**Comment by lostallmymoney** [comment]
Should be fixed for good. You can add naga start to the startup commands to make it run at startup.

**Comment by SirFireball3521** [comment]
Late reply, but I haven't had any issues since this was made. Don't know what caused it but oh well.
