### ISSUE TITLE
xdotool freezes

### ISSUE THREAD

**Issue by lostallmymoney** [lostallmymoney/Razer_Mouse_Linux#7]
xdotool seems to be freezing when writing symbols. I'll try to remove the xdotool dependency tomorrow.

**Comment by ScoreUnder** [comment]
are these symbols being parsed by the shell? e.g. `[`, `$`, `(`, `"`, `` ` `` etc.

If so you might be using the wrong key name (e.g. those ones should be `bracketleft`, `dollar`, `parenleft`, `quotedbl`, `grave` etc respectively)

**Comment by lostallmymoney** [comment]
I'll see if I can get xdotool to write them without freezing but after a lot of investigation i realised the freeze comes from the x server because when the symbol isn't mapped to any key it has to assign it to the keyboard virtually.
I think we'd need a literal virtual keyboard with keys assigned when the config loads to avoid this issue. I started writing something without xdotool but it had the same kind of issue :/

 like having the keys as hex numbers because you can put simple strings with symbols in the config file and then convert it to hex array. If there is a way to write symbols without the freeze maybe we can implement it ;) I'll try with the whole key names later.

**Comment by lostallmymoney** [comment]
Imma try implementing something like this https://wiki.archlinux.org/title/Xmodmap some day
